name: Update Submodules

# Trigger the workflow on every push to the 'main' branch
on:
  push:
    branches:
      - main  # You can change this to any branch you want

jobs:
  update-submodules:
    runs-on: ubuntu-latest  # The runner that will execute this job

    steps:
      # Step 1: Checkout the code and submodules
      - name: Checkout code and submodules
        uses: actions/checkout@v3
        with:
          submodules: 'true'  # This ensures submodules are checked out

      # Step 2: Update submodules to the latest commit
      - name: Update submodules
        run: |
          git submodule update --remote --merge --recursive
          
      # Step 3: Commit and push changes back to the repository
      - name: Commit and push submodule updates
        run: |
          git add .
          git commit -m "Automatically update submodule references"
          git push
        env:
          # Set up GitHub token for authentication (this is needed to push changes back)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token

