name: Update Submodules

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  push:
    branches:
      - main # Adjust this to your default branch if different

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive # Recursively update submodules
    
    - name: Set up Git user
      run: |
        git config --global user.email "nikhilgaruda@live.com"
        git config --global user.name "Nikhil Garuda"

    - name: Update submodule
      run: |
        git submodule update --remote --merge
        if [-n "$(git status --porcelain)"]; then
          git add .
          git commit -m "Daily update of submodule"
          git push
        else
          echo "No changes in submodule"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
